name: CI run tests

on:
    push:
    pull_request:

env:
    database_uri: "sqlite+aiosqlite:///:memory:"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install project
              run: uv sync --locked --all-extras --dev

            - name: Run tests
              run: uv run pytest --cov
